model_metadata:
  tags:
  - openai-compatible
model_name: qwen3-8b-pool
python_version: py313
resources:
  accelerator: H100
  cpu: '1'
  memory: 10Gi
  use_gpu: true
trt_llm:
  build:
    base_model: decoder
    checkpoint_repository:
      repo: Qwen/Qwen3-8B
      source: HF
    max_seq_len: 8192
    quantization_type: fp8_kv
    tensor_parallel_count: 1
  runtime:
    kv_cache_free_gpu_mem_fraction: 0.9
    served_model_name: qwen3-8b
